    <div id="header">
      <div id="logo">
        <h1><a href="/"><b>MarkdownShare</b></a></h1>
        <h4>Simple sharing of markdown text</h4>
      </div>
      <div id="links">
        <ul>
          <li><a href="/" title="Home">Home</a></li>
          <li><a href="/create/" title="Create">Create</a></li>
          <li><a href="/cheatsheet/" title="Markdown Cheatsheet">Cheatsheet</a></li>
        </ul>
      </div>
    </div>

